version: '3.8'

services:
  kovasoft:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kovasoft-website
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - kovasoft-network

networks:
  kovasoft-network:
    driver: bridge

